print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')
print('Good Morning!')

print('Good afternoon!')
print('Good afternoon!')
print('Good afternoon!')
print('Good afternoon!')
print('Good afternoon!')

print('Good night!')
print('Good night!')
print('Good night!')
print('Good night!')
print('Good night!')