print("귀도 반 로섬")
print("파이썬의 특징: 높은 확장성과 이식성")
print("")
print("https://www.python.org/")
print("")
print("7 * 1 = 7")
print("7 * 2 = 14")
print("....")
print("7 * 9 = 63")
print("")
print("삼각형의 넓이 : ",10*25/2)
print("사각형의 넓이 : ",5*15)
print("")
print("24-05-14 가장 인상깊었던 일은.. 내일이 쉬는날이라는 것")
print("나의 정보 : gbheaven")
print("2024-05-14")